#! /bin/bash

# ** Install Dependences

# Before you begin, you need to install the software that Git depends on
# sudo apt update -y
sudo apt install -y git unzip

# ** Setting Up Git (it may not be needed)

git config --global user.name "Guilherme"
git config --global user.email "soulkanarprograms@gmail.com"

# ** Download dotfile repository
git clone --bare https://github.com/soulkanarprograms/.cfg.git ~/.cfg
sed -i 's/github/soulkanarprograms:str0g0n0ff@github/g' ~/.cfg/config

function config {
   /usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME $@
}
mkdir -p .config-backup
config checkout
if [ $? = 0 ]; then
  echo "Checked out config.";
  else
    echo "Backing up pre-existing dot files.";
    config checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} mv {} .config-backup/{}
fi;
config checkout
config config status.showUntrackedFiles no

# ** Start Installation
# sudo chmod +x install.sh
# ./install.sh

mkdir ~/.config

# ** Install VIM 8
sudo add-apt-repository ppa:jonathonf/vim -y
sudo apt update -y
sudo apt install vim -y

# ** Install zsh
sudo apt install -y zsh

# ** Install vifm
sudo apt-get install -y vifm

# ** Install Oh-My-Zsh
sudo apt-get install -y powerline fonts-powerline

git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.config/.oh-my-zsh

cp ~/.config/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc

chsh -s /bin/zsh

cd ~/.config/.oh-my-zsh

# ** Sintax Highlight
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "$HOME/.config/.zsh-syntax-highlighting" --depth 1
echo "source $HOME/.config/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> "$HOME/.config/.zshrc"
sed -i 's/robbyrussell/agnoster/g' ~/.zshrc
sed -i 's/export ZSH=$HOME/.oh-my-zsh/export ZSH=$HOME/.config/.oh-my-zsh/g' ~/.zshrc
