#! /bin/bash

# ** Install Dependences

# Before you begin, you need to install the software that Git depends on
# sudo apt update -y
sudo apt install -y git unzip

# ** Setting Up Git (it may not be needed)

git config --global user.name "Guilherme"
git config --global user.email "soulkanarprograms@gmail.com"

# ** Download dotfile repository
git clone --bare https://github.com/soulkanarprograms/.cfg.git ~/.cfg
sed -i 's/github/soulkanarprograms:str0g0n0ff@github/g' ~/.cfg/config

function config {
   /usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME $@
}
mkdir -p .config-backup
config checkout
if [ $? = 0 ]; then
  echo "Checked out config.";
  else
    echo "Backing up pre-existing dot files.";
    config checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} mv {} .config-backup/{}
fi;
config checkout
config config status.showUntrackedFiles no

# ** Change permission of all installation files
sudo chmod +x $PWD/.minimal_install
sudo chmod +x $PWD/.server_install
sudo chmod +x $PWD/.gui_install
