#! /bin/bash

# Create base directory
mkdir ~/.config

# ** Install VIM 8
sudo add-apt-repository ppa:jonathonf/vim -y
sudo apt update -y
sudo apt install vim -y

# ** Install zsh
sudo apt install -y zsh

# ** Install vifm
sudo apt-get install -y vifm

# ** Install Oh-My-Zsh
	cp ~/.zshrc ~/.zshrc.orig

	export ZSH=~/.config/.oh-my-zsh
	git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.config/.oh-my-zsh
	cp ~/.config/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc
	echo "export TERM='xterm-256color'" >> "$HOME/.zshrc"
	sed -i 's/robbyrussell/agnoster/' ~/.zshrc
	sed -i 's/export ZSH=\$HOME\/.oh-my-zsh/export ZSH=\$HOME\/.config\/.oh-my-zsh/g' ~/.zshrc
	
	chsh -s /bin/zsh

	cd ~/.config/.oh-my-zsh

	# ** Sintax Highlight
	export ZSH_CUSTOM=~/.config/.oh-my-zsh/custom	
	git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $ZSH_CUSTOM/plugins/zsh-syntax-highlighting
	echo "source $ZSH/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> "$HOME/.zshrc"
	
	# ** Zsh AutoSuggestion
	git clone https://github.com/zsh-users/zsh-autosuggestions $ZSH_CUSTOM/plugins/zsh-autosuggestions
	echo "source $ZSH/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh" >> "$HOME/.zshrc"

# ** Creating alias

mkdir -p ~/.config/system
echo "alias config='/usr/bin/git --git-dir=/home/guilherme/.cfg/ --work-tree=/home/guilherme'"  >> "$HOME/.config/system/.alias"
echo "source $HOME/.config/system/.alias" >> "$HOME/.zshrc"

