#! /bin/bash

# Create base directory
mkdir ~/.config

# ** Install VIM 8
sudo add-apt-repository ppa:jonathonf/vim -y
sudo apt update -y
sudo apt install vim -y

# ** Install zsh
mkdir ~/.config/zsh
sudo apt install -y zsh
export ZDOTDIR=$HOME/.config/zsh
mv ~/.zshrc $ZDOTDIR

# ** Install vifm
sudo apt-get install -y vifm

# ** Install Oh-My-Zsh
	cp $ZDOTDIR/.zshrc $ZDOTDIR/.zshrc.orig

	export ZSH=~/.config/oh-my-zsh
	git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.config/oh-my-zsh
	cp ~/.config/oh-my-zsh/templates/zshrc.zsh-template $ZDOTDIR/.zshrc
	echo "export TERM='xterm-256color'" >> "$ZDOTDIR/.zshrc"
	sed -i 's/robbyrussell/agnoster/' $ZDOTDIR/.zshrc
	sed -i 's/export ZSH=\$HOME\/.oh-my-zsh/export ZSH=\$HOME\/.config\/oh-my-zsh/g' $ZDOTDIR/.zshrc
	
	chsh -s /bin/zsh

	cd ~/.config/oh-my-zsh

	# ** Sintax Highlight
	export ZSH_CUSTOM=~/.config/oh-my-zsh/custom	
	git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $ZSH_CUSTOM/plugins/zsh-syntax-highlighting
	echo "source $ZSH/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> "$ZDOTDIR/.zshrc"
	
	# ** Zsh AutoSuggestion
	git clone https://github.com/zsh-users/zsh-autosuggestions $ZSH_CUSTOM/plugins/zsh-autosuggestions
	echo "source $ZSH/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh" >> "$ZDOTDIR/.zshrc"

# ** Creating alias

mkdir -p ~/.config/system
echo "alias config='/usr/bin/git --git-dir=/home/guilherme/.cfg/ --work-tree=/home/guilherme'"  >> "$HOME/.config/system/.alias"
echo "source $HOME/.config/system/.alias" >> "$ZDOTDIR/.zshrc"

